credentials:
  usernames:
    lsouza:
      email: lsouzadasilva4@gmail.com
      logged_in: False
      name: Leandro Souza
      password: abcd1234
    randrade:
      email: testando1@gmail.com
      logged_in: False
      name: Raquel Barreto
      password: abcd1234
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
